/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryUnifiedAPI.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Unified API (unified/v1)
// Description:
//   Sample combined API.
// Classes:
//   GTLQueryUnifiedAPI (5 custom class methods, 5 custom properties)

#import "GTLQueryUnifiedAPI.h"

#import "GTLUnifiedAPIErrorSpec.h"
#import "GTLUnifiedAPISerializedKey.h"
#import "GTLUnifiedAPISerializedQueryResponse.h"

@implementation GTLQueryUnifiedAPI

@dynamic fields, key, message, name, options;

#pragma mark - Service level methods
// These create a GTLQueryUnifiedAPI object.

+ (instancetype)queryForCreateWithMessage:(NSString *)message
                                     name:(NSString *)name {
  NSString *methodName = @"unified.create";
  GTLQueryUnifiedAPI *query = [self queryWithMethodName:methodName];
  query.message = message;
  query.name = name;
  query.expectedObjectClass = [GTLUnifiedAPISerializedKey class];
  return query;
}

+ (instancetype)queryForDeleteWithKey:(NSString *)key {
  NSString *methodName = @"unified.delete";
  GTLQueryUnifiedAPI *query = [self queryWithMethodName:methodName];
  query.key = key;
  return query;
}

+ (instancetype)queryForErrors {
  NSString *methodName = @"unified.errors";
  GTLQueryUnifiedAPI *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLUnifiedAPIErrorSpec class];
  return query;
}

+ (instancetype)queryForList {
  NSString *methodName = @"unified.list";
  GTLQueryUnifiedAPI *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLUnifiedAPISerializedQueryResponse class];
  return query;
}

+ (instancetype)queryForUpdateWithKey:(NSString *)key
                              message:(NSString *)message {
  NSString *methodName = @"unified.update";
  GTLQueryUnifiedAPI *query = [self queryWithMethodName:methodName];
  query.key = key;
  query.message = message;
  return query;
}

@end
