/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUnifiedAPIErrorSpec.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Unified API (unified/v1)
// Description:
//   Sample combined API.
// Classes:
//   GTLUnifiedAPIErrorSpec (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLUnifiedAPIServiceError;

// ----------------------------------------------------------------------------
//
//   GTLUnifiedAPIErrorSpec
//

@interface GTLUnifiedAPIErrorSpec : GTLObject
@property (nonatomic, retain) NSArray *errors;  // of GTLUnifiedAPIServiceError
@end
