/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUnifiedAPISerializedQueryResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Unified API (unified/v1)
// Description:
//   Sample combined API.
// Classes:
//   GTLUnifiedAPISerializedQueryResponse (0 custom class methods, 2 custom properties)

#import "GTLUnifiedAPISerializedQueryResponse.h"

#import "GTLUnifiedAPISerializedDatastoreObject.h"

// ----------------------------------------------------------------------------
//
//   GTLUnifiedAPISerializedQueryResponse
//

@implementation GTLUnifiedAPISerializedQueryResponse
@dynamic count, items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLUnifiedAPISerializedDatastoreObject class]
  };
  return map;
}

@end
