/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUnifiedAPISerializedKey.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Unified API (unified/v1)
// Description:
//   Sample combined API.
// Classes:
//   GTLUnifiedAPISerializedKey (0 custom class methods, 2 custom properties)

#import "GTLUnifiedAPISerializedKey.h"

// ----------------------------------------------------------------------------
//
//   GTLUnifiedAPISerializedKey
//

@implementation GTLUnifiedAPISerializedKey
@dynamic encoded, kind;
@end
