/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUnifiedAPISerializedQueryResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Unified API (unified/v1)
// Description:
//   Sample combined API.
// Classes:
//   GTLUnifiedAPISerializedQueryResponse (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLUnifiedAPISerializedDatastoreObject;

// ----------------------------------------------------------------------------
//
//   GTLUnifiedAPISerializedQueryResponse
//

// This class supports NSFastEnumeration over its "items" property. It also
// supports -itemAtIndex: to retrieve individual objects from "items".

@interface GTLUnifiedAPISerializedQueryResponse : GTLCollectionObject
@property (nonatomic, retain) NSNumber *count;  // intValue
@property (nonatomic, retain) NSArray *items;  // of GTLUnifiedAPISerializedDatastoreObject
@end
