/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUnifiedAPISerializedKey.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Unified API (unified/v1)
// Description:
//   Sample combined API.
// Classes:
//   GTLUnifiedAPISerializedKey (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLUnifiedAPISerializedKey
//

@interface GTLUnifiedAPISerializedKey : GTLObject
@property (nonatomic, copy) NSString *encoded;
@property (nonatomic, copy) NSString *kind;
@end
