/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUnifiedAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Unified API (unified/v1)
// Description:
//   Sample combined API.

#import "GTLUnifiedAPIConstants.h"

#import "GTLUnifiedAPIErrorSpec.h"
#import "GTLUnifiedAPISerializedDatastoreObject.h"
#import "GTLUnifiedAPISerializedKey.h"
#import "GTLUnifiedAPISerializedQueryResponse.h"
#import "GTLUnifiedAPIServiceError.h"

#import "GTLQueryUnifiedAPI.h"
#import "GTLServiceUnifiedAPI.h"
