/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUnifiedAPIConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Unified API (unified/v1)
// Description:
//   Sample combined API.

#import "GTLUnifiedAPIConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeUnifiedAPIUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
