/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUnifiedAPIServiceError.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Unified API (unified/v1)
// Description:
//   Sample combined API.
// Classes:
//   GTLUnifiedAPIServiceError (0 custom class methods, 0 custom properties)

#import "GTLUnifiedAPIServiceError.h"

// ----------------------------------------------------------------------------
//
//   GTLUnifiedAPIServiceError
//

@implementation GTLUnifiedAPIServiceError
@end
