/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUnifiedAPIErrorSpec.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Unified API (unified/v1)
// Description:
//   Sample combined API.
// Classes:
//   GTLUnifiedAPIErrorSpec (0 custom class methods, 1 custom properties)

#import "GTLUnifiedAPIErrorSpec.h"

#import "GTLUnifiedAPIServiceError.h"

// ----------------------------------------------------------------------------
//
//   GTLUnifiedAPIErrorSpec
//

@implementation GTLUnifiedAPIErrorSpec
@dynamic errors;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"errors" : [GTLUnifiedAPIServiceError class]
  };
  return map;
}

@end
